name: Build

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      
      - uses: msys2/setup-msys2@v2
        with:
          install: |
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-libwebp
            mingw-w64-x86_64-libsharpyuv

      - shell: bash
        run: |
          GOROOT_MSYS=$(cygpath -u "$(go env GOROOT)")
          echo "GOROOT_MSYS=$GOROOT_MSYS" >> $GITHUB_ENV

      - shell: msys2 {0}
        env:
          GOOS: 'windows'
          GOARCH: 'amd64'
          CGO_CFLAGS: '-I/mingw64/include'
          CGO_LDFLAGS: '-L/mingw64/lib -lwebp -lsharpyuv -static-pie'
        run: |
          export PATH="$GOROOT_MSYS/bin:$PATH"
          go build -ldflags='-s -w -extldflags "-static"' -trimpath -buildmode=pie -o ./ccfolia-room-minifier.exe ./cmd/main.go

      - uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: ccfolia-room-minifier.exe
