name: Build WASM

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Install libwebp
        env:
          LIBWEBP_VERSION: 1.4.0
        run: |
          wget https://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-${{ env.LIBWEBP_VERSION }}.tar.gz
          tar xvf libwebp-${{ env.LIBWEBP_VERSION }}.tar.gz
          cd libwebp-${{ env.LIBWEBP_VERSION }}
          ./configure
          make
          sudo make install

      - name: Build
        run: |
          GOOS=js GOARCH=wasm go build -ldflags="-s -w" -trimpath -buildmode=pie -o ./dist/ccfolia-room-minifier.wasm ./ccfolia-room-minifier.go
          cp '$(go env GOROOT)/misc/wasm/wasm_exec.js' ./dist/

      - uses: actions/upload-artifact@v3
        with:
          path: dist/

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.url }}

    steps:
      - uses: actions/deploy-pages@v4
