name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: windows-latest
            goos: windows
            goarch: amd64
            extension: '.exe'
          - os: macos-latest
            goos: darwin
            goarch: [amd64, arm64]
            extension: '-darwin'
          - os: ubuntu-latest
            goos: linux
            goarch: [amd64, arm64]
            extension: '-linux'

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      
      - if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          install: |
            gcc
            libwebp
      
      - if: runner.os == 'macos'
        run: brew install webp
      
      - if: runner.os == 'ubuntu'
        run: sudo apt-get install -y libwebp-dev
      
      - env:
          CGO_ENABLED: 1
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: go build -o ccfolia-room-minifier${{ matrix.extension }} ccfolia-room-minifier.go

      - uses: softprops/action-gh-release@v2
        with:
          files: ccfolia-room-minifier${{ matrix.extension }}
