name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    strategy:
      matrix:
        include:
          - os: windows-latest
            goos: windows
            goarch: amd64
            suffix: '.exe'
          - os: macos-latest
            goos: darwin
            goarch: arm64
            suffix: '-darwin-arm64'
          - os: ubuntu-latest
            goos: linux
            goarch: amd64
            suffix: '-linux-amd64'
    
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      
      - if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          install: |
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-libwebp
      - if: runner.os == 'Windows'
        shell: bash
        run: |
          GOROOT_MSYS=$(cygpath -u "$(go env GOROOT)")
          echo "GOROOT_MSYS=$GOROOT_MSYS" >> $GITHUB_ENV

      - if: runner.os == 'macOS'
        run: brew install webp
      
      - if: runner.os == 'Linux'
        run: |
          wget https://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-1.4.0.tar.gz
          tar xvf libwebp-1.4.0.tar.gz
          cd libwebp-1.4.0
          ./configure
          make
          sudo make install

      - if: runner.os == 'Windows'
        shell: msys2 {0}
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_LDFLAGS: '-static'
        run: |
          export PATH="$GOROOT_MSYS/bin:$PATH"
          go build -ldflags='-s -w -extldflags "-static"' -o ccfolia-room-minifier${{ matrix.suffix }} ccfolia-room-minifier.go

      - if: runner.os != 'Windows'
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: go build -o ccfolia-room-minifier${{ matrix.suffix }} ccfolia-room-minifier.go

      - uses: softprops/action-gh-release@v2
        with:
          files: ccfolia-room-minifier${{ matrix.suffix }}
